#!/bin/sh

set -e
olddir=$(pwd)
dir=$1

case "$dir" in
  *.tgz|*.gz)
    dir=$(mktemp -d -t samusXXXX)
    trap "rm -rf $dir" 0
    tar -xzf $* -C $dir
  ;;
esac

cd $dir
echo "-----BEGIN RSA PRIVATE KEY-----" > .sshkey
echo "$__CREDS_KEY" | fold -w 65 >> .sshkey
echo "-----END RSA PRIVATE KEY-----" >> .sshkey
chmod 400 .sshkey

for r in $_REMOTES; do
  ssh-agent sh -c "ssh-add .sshkey; git push $r $_REFS"
done
cd $olddir
