#!/bin/sh

set -e
olddir=$(pwd)
dir=$1

case "$dir" in
  *.tgz|*.gz)
    dir=$(mktemp -d -t samusXXXX)
    trap "rm -rf $dir" 0
    tar -xzf $* -C $dir
  ;;
esac

cd $dir
for r in $_remotes; do
  git push $r $_refs
done
cd $olddir
