#!/bin/sh

export AWS_ACCESS_KEY_ID=$__CREDS_KEY
export AWS_SECRET_ACCESS_KEY=$__CREDS_SECRET

set -e
for f in $*; do
  recursive=""
  if [ -d $f ]; then
    recursive="--recursive"
  fi
  aws s3 cp $recursive --acl public-read --region $_REGION $f s3://$_BUCKET/$_PREFIX$_KEY
done
