#!/usr/bin/env ruby

ENV['AWS_ACCESS_KEY_ID'] = ENV['__creds_key']
ENV['AWS_SECRET_ACCESS_KEY'] = ENV['__creds_secret']

require 'aws-sdk-core'

Aws.config[:region] = ENV['_region']
Aws.cloudfront.create_invalidation(
  distribution_id: ENV['_distribution'],
  invalidation_batch: {
    paths: {
      quantity: ARGV.size,
      items: ARGV },
    caller_reference: Time.now.to_s
  })
