#!/bin/sh

export AWS_ACCESS_KEY_ID=$__creds_principal
export AWS_SECRET_ACCESS_KEY=$__creds_credential

set -e
for f in $*; do
  recursive=""
  if [ -d $f ]; then
    recursive="--recursive"
  fi
  aws s3 cp $recursive --acl public-read --region $_region $f s3://$_bucket/$_prefix$_key
done
